import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | AI Girlfriend Chat',
  description: 'Terms of Service for AI Girlfriend Chat - Read our terms and conditions.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen py-12 px-4">
      {/* Background decoration */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-gf-pink-500/10 rounded-full blur-3xl" />
        <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-gf-purple-500/10 rounded-full blur-3xl" />
      </div>

      <div className="relative max-w-3xl mx-auto">
        {/* Back button */}
        <Link
          href="/"
          className="mb-8 inline-flex items-center gap-2 text-white/60 hover:text-white transition-colors"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Back to Chat
        </Link>

        <div className="glass rounded-2xl p-8">
          <h1 className="text-3xl font-display font-bold gradient-text mb-8">Terms of Service</h1>
          
          <div className="space-y-6 text-white/70">
            <p className="text-sm text-white/50">Last updated: {new Date().toLocaleDateString()}</p>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing and using AI Girlfriend Chat, you agree to be bound by these Terms of Service. 
                If you do not agree to these terms, please do not use our service. We reserve the right to 
                modify these terms at any time, and your continued use of the service constitutes acceptance 
                of any changes.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
              <p>
                AI Girlfriend Chat provides an AI-powered virtual companion chat experience. Our service uses 
                artificial intelligence to simulate conversational interactions. The AI is not a real person 
                and responses are generated by machine learning algorithms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">3. Eligibility</h2>
              <p>
                You must be at least 18 years old to use this service. By using AI Girlfriend Chat, you 
                represent and warrant that you are at least 18 years of age and have the legal capacity 
                to enter into these Terms of Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">4. User Conduct</h2>
              <p className="mb-3">You agree not to use the service to:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Violate any applicable laws or regulations</li>
                <li>Attempt to bypass or circumvent any usage limits or payment requirements</li>
                <li>Use the service for any illegal, harmful, or abusive purposes</li>
                <li>Attempt to reverse engineer, decompile, or extract the AI model</li>
                <li>Share or distribute content generated by the service in ways that violate these terms</li>
                <li>Impersonate any person or entity</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">5. Credits and Payments</h2>
              <p className="mb-3">Our service operates on a credit-based system:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>New users receive a limited number of free messages</li>
                <li>Additional credits or unlimited access can be purchased</li>
                <li>All purchases are final and non-refundable unless required by law</li>
                <li>Subscription plans may be cancelled at any time, with access continuing until the end of the billing period</li>
                <li>Prices are subject to change with notice</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">6. Intellectual Property</h2>
              <p>
                All content, features, and functionality of the service, including but not limited to text, 
                graphics, logos, and software, are owned by AI Girlfriend Chat and are protected by 
                intellectual property laws. You may not copy, modify, distribute, or create derivative 
                works without our express written permission.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">7. AI-Generated Content</h2>
              <p>
                The responses generated by our AI are created algorithmically and may not always be accurate, 
                appropriate, or reflect real-world information. You understand that AI-generated content 
                should not be relied upon for advice, and you use the service at your own discretion.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">8. Disclaimer of Warranties</h2>
              <p>
                THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, 
                EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, 
                SECURE, OR ERROR-FREE. YOUR USE OF THE SERVICE IS AT YOUR OWN RISK.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">9. Limitation of Liability</h2>
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, AI GIRLFRIEND CHAT SHALL NOT BE LIABLE FOR ANY 
                INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR 
                RELATED TO YOUR USE OF THE SERVICE, REGARDLESS OF WHETHER WE HAVE BEEN ADVISED OF 
                THE POSSIBILITY OF SUCH DAMAGES.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">10. Termination</h2>
              <p>
                We reserve the right to terminate or suspend your access to the service at any time, 
                without notice, for conduct that we believe violates these Terms of Service or is 
                harmful to other users, us, or third parties, or for any other reason at our sole discretion.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">11. Governing Law</h2>
              <p>
                These Terms of Service shall be governed by and construed in accordance with the laws 
                of the United States, without regard to its conflict of law provisions.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">12. Contact Information</h2>
              <p>
                If you have any questions about these Terms of Service, please contact us through{' '}
                <Link href="/contact" className="text-gf-pink-400 hover:underline">our contact page</Link>.
              </p>
            </section>
          </div>
        </div>

        {/* Footer Links */}
        <div className="mt-8 flex justify-center gap-6 text-sm text-white/40">
          <Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
          <Link href="/contact" className="hover:text-white transition-colors">Contact</Link>
        </div>
      </div>
    </div>
  );
}
